### ISSUE TITLE
NTFS ADS separator (':') in file name is forbidden

### ISSUE THREAD

**Issue by onthebridgetonowhere** [zeljkoobrenovic/sokrates#27]
I would like to report an issue when encountering malformed filenames. I am trying to run the tool on `github.com/apache/incubator-retired-blur` project, and I get the following exception: 

```
[main] INFO nl.obren.sokrates.sourcecode.analysis.files.FileHistoryAnalyzer - Analyzing files changed together in past 180 days...
java.lang.IllegalArgumentException: NTFS ADS separator (':') in file name is forbidden.
        at org.apache.commons.io.FilenameUtils.indexOfExtension(FilenameUtils.java:737)
        at org.apache.commons.io.FilenameUtils.getExtension(FilenameUtils.java:1057)
        at nl.obren.sokrates.sourcecode.githistory.FileUpdate.getExtension(FileUpdate.java:52)
        at nl.obren.sokrates.sourcecode.githistory.GitHistoryPerExtensionUtils.lambda$getCommitsPerExtensions$0(GitHistoryPerExtensionUtils.java:21)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
        at nl.obren.sokrates.sourcecode.githistory.GitHistoryPerExtensionUtils.getCommitsPerExtensions(GitHistoryPerExtensionUtils.java:20)
        at nl.obren.sokrates.sourcecode.contributors.GitContributorsUtil.getCommitsPerExtension(GitContributorsUtil.java:47)
        at nl.obren.sokrates.sourcecode.analysis.FileHistoryAnalysisConfig.getCommitsPerExtension(FileHistoryAnalysisConfig.java:84)
        at nl.obren.sokrates.sourcecode.analysis.files.ContributorsAnalyzer.analyze(ContributorsAnalyzer.java:46)
        at nl.obren.sokrates.sourcecode.analysis.CodeAnalyzer.analyze(CodeAnalyzer.java:75)
        at nl.obren.sokrates.cli.CommandLineInterface.generateReports(CommandLineInterface.java:506)
        at nl.obren.sokrates.cli.CommandLineInterface.generateReports(CommandLineInterface.java:268)
        at nl.obren.sokrates.cli.CommandLineInterface.run(CommandLineInterface.java:116)
        at nl.obren.sokrates.cli.CommandLineInterface.main(CommandLineInterface.java:68)
```

I run Windows 10 with Java 11, and downloaded the `sokrates` jar file today. 

Is it possible to perhaps ignore some of these ill-named files and maybe keep a list with files that were not properly processed during the analysis? 

Btw, the tool is great. Thanks for the huge effort in developing and maintaining it!!!

**Comment by onthebridgetonowhere** [comment]
One workaround to this issue is to run the tool on a Linux machine. That should get rid of the error.

**Comment by zeljkoobrenovic** [comment]
Can you try the laters version (from today)? It should fix the issue.

**Comment by onthebridgetonowhere** [comment]
Thanks @zeljkoobrenovic. I'll try and report back.

**Comment by onthebridgetonowhere** [comment]
@zeljkoobrenovic the latest changes seem to have fixed the issue, thanks for the quick fix!
